pipeline:
  build:
    image: python:3.5.1-alpine
    commands:
      - pip wheel -r requirements.txt
      - pip wheel -r test-requirements.txt
      - python setup.py install
      - flake8 dronedemo
      - mkdir -p coverage
      - nosetests -v tests/
